name: tasker
description: Let your device plan your day.

publish_to: 'none'

version: 0.1.0-alpha.168

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_sign_in: ^5.0.1
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0

  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  path_provider: ^2.0.1
  hive: ^2.0.2
  url_launcher: ^6.0.3

  slikker_kit: #^1.0.7
    path: "../slikker_kit/"  

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/app_icon.png'
  adaptive_icon_foreground: 'assets/app_icon_foreground.png'
  adaptive_icon_background: "#7373FF"

flutter:
  uses-material-design: true
  fonts:
  - family:  AppIcons
    fonts:
      - asset: fonts/AppIcons.ttf    

  - family: Manrope
    fonts:
      - asset: fonts/Manrope-Bold.ttf